import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <main className={"bg-gray-100 min-h-screen w-screen text-black"}>
      <main className={"max-w-screen-2xl m-auto bg-white"}>
      {/* NAVBAR */}
      <nav className={"bg-white p-2 flex justify-between"}>
        <a href="" className={"font-bold text-gray-700 text-2xl"}>
          ReserveTable
        </a>
        <div>
          <div className={"flex"}>
          <button className={"bg-blue-400 text-white border p-1 px-4 rounded mr-3"}>Sign In</button>
          <button className={"text-black border p-1 rounded"}>Sign up</button>
          </div>
        </div>
      </nav>
      {/* NAVBAR */}
      {/* HEADER */}
      <div className="h-96 overflow-hidden">
        <div className="bg-center bg-gradient-to-r from-[#0f1f47] to-[#5f6984] h-full flex justify-center items-center">
          <h1 className="text-7xl text-white capitalize text-shadow text-center">
            MilesStone Grill (Toronto)
          </h1>
        </div>
      </div>
      {/* HEADER */}
      {/* DESCRIPTION PORTION */}
      <div className="flex m-auto w-2/3 justify-between items-start 0 -mt-11">
        <div className="bg-white rounded p-3 shadow w-[70%]">
        {/* RESTAURANT NAV */}
          <nav className="flex text-reg border-b pb-2">
            <a href="" className="mr-7" >Menu</a>
            <a href="" className="mr-7" >Overview</a>
          </nav>
        {/* RESTAURANT NAV */}
        {/* TITLE */}
          <div className="mt-4 border-b pb-6">
            <h1 className='font-bold text-6xl'>MilesStone Grill</h1>
          </div>
        {/* TITLE */}
        {/* RATINGS */}
        <div className="flex items-end">
          <div className="ratings mt-2 flex items-center">
            <p>*****</p>
            <p className="text-reg ml-3">4.9</p>
          </div>
          <div>
            <p className="text-reg-ml-4">600 Reviews</p>
          </div>
        </div>
        {/* RATINGS */}
        </div>
      </div>
      {/* DESCRIPTION PORTION */}
      </main>
    </main>
    </>
  )
}
